version: 2.1

jobs:
  test:
    parameters:
      python-version:
        type: string
      numpy-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>-node
    steps:
      - checkout

      - run:
          name: Install Poetry
          command: |
            pip install --upgrade pip
            pip install poetry

      - run:
          name: Configure Poetry
          command: |
            poetry --version
            poetry config virtualenvs.in-project true

      - run:
          name: Install dependencies (Poetry)
          command: |
            poetry install --no-interaction

      - run:
          name: Install supported NumPy version
          command: |
            poetry run pip install "numpy==<< parameters.numpy-version >>"
            poetry run pip check

      - run:
          name: Run tests
          command: |
            poetry run pytest tests

workflows:
  version: 2
  test:
    jobs:
      - test:
          name: python-3.12-numpy-2.0.2
          python-version: "3.12"
          numpy-version: "2.0.2"
      - test:
          name: python-3.13-numpy-2.1.0
          python-version: "3.13"
          numpy-version: "2.1.0"
      - test:
          name: python-3.14-numpy-2.3.4
          python-version: "3.14"
          numpy-version: "2.3.4"
